//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MARKEPLACE.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RocketMarketsEntities : DbContext
    {
        public RocketMarketsEntities()
            : base("name=RocketMarketsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<afiliado> afiliado { get; set; }
        public virtual DbSet<distrito> distrito { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<provincia> provincia { get; set; }
        public virtual DbSet<sexo> sexo { get; set; }
        public virtual DbSet<tipo_empresa> tipo_empresa { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
