//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MARKEPLACE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int codigo { get; set; }
        public string nombres { get; set; }
        public Nullable<int> idpais { get; set; }
        public Nullable<int> idsexo { get; set; }
        public string email { get; set; }
        public string contraseña { get; set; }
        public string confir_contraseña { get; set; }
    
        public virtual pais pais { get; set; }
        public virtual sexo sexo { get; set; }
    }
}
